### ISSUE TITLE
Support Continuous Profiler

### ISSUE THREAD

**Issue by jwyza-pi** [DataDog/datadog-aas-extension#170]
As far as I can tell, the continuous profiling described here https://docs.datadoghq.com/profiler/enabling/dotnet/ only works on dedicated hosts/VMs/etc.  It doesn't work with azure App Services via the extension even if the environment variables to turn the profiler on are set.

**Comment by gleocadie** [comment]
Hello

Can you be more specific please ? We have a .NET application that runs in our AAS environment with the profiler attached to it.

There is nothing specific to dedicated hosts/VM/etc for the profiler, the environment variables are the same on all those environments.

**Comment by jwyza-pi** [comment]
Apologies, it seems like this support must have been added recently.  When I looked into it a couple months ago, I was told it didn't work (and in fact it didn't as far as support could tell), but it seems to now.  (I should have tested it again before opening the ticket, assumed that since I hadn't gotten a message from support on it, it was still broken).  It doesn't seem to support anything more than CPU % and Wall Time, so it's still in its infancy I guess, but definitely nice to have it functioning now. 

Thanks!

**Comment by gleocadie** [comment]
> Apologies, it seems like this support must have been added recently. When I looked into it a couple months ago, I was told it didn't work (and in fact it didn't as far as support could tell), but it seems to now. (I should have tested it again before opening the ticket, assumed that since I hadn't gotten a message from support on it, it was still broken). It doesn't seem to support anything more than CPU % and Wall Time, so it's still in its infancy I guess, but definitely nice to have it functioning now.
> 
> Thanks!

No problem.
About the features, you are right CPU and Wall Time are enabled by default, but you can enable other profiles too (ex: Exception, Allocation...) by setting specific environment variables. See the [documentation ](https://docs.datadoghq.com/profiler/enabling/dotnet/?tab=windows)for more info
![image](https://user-images.githubusercontent.com/17292193/214316175-e7c9bd4a-df83-48c9-9455-baebd2bd75cb.png)

and keep it mind that 
![image](https://user-images.githubusercontent.com/17292193/214316385-cad4757a-8433-42d5-829c-e95e8133aa0a.png)

**Comment by jwyza-pi** [comment]
Wow, I feel really dumb now!  Thank you so much!
