### ISSUE TITLE
Tracking Deployments 

### ISSUE THREAD

**Issue by bheemreddy181** [DataDog/datadog-aas-extension#187]
Hey Team , 

if we are using AAS extension for tracking automating tracing data, how can we track the deployments when these apps are deployed via Azure pipeline stages ?

More interms of https://docs.datadoghq.com/tracing/services/deployment_tracking/

**Comment by dmmusil** [comment]
We set `DD_VERSION` during the deployment and that flows to the APM data.

**Comment by bheemreddy181** [comment]
Makes sense thanks @dmmusil I was able to inject the data same way.
