### ISSUE TITLE
Datadog AAS for Windows/.NET dramatic increase in application latency

### ISSUE THREAD

**Issue by jshrack-aya** [DataDog/datadog-aas-extension#195]
Hi!

When we deploy the Datadog AAS extension into our web and application API app services we have noticed a dramatic increase in overall application response times, latency, and also what appears to be a memory/handle/thread leak which ultimately leads to extremely poor overall application performance and often requires a restart of said applications. Once we remove the extension response times flatten out to expected norms. We have removed profiling and ASM features and we continue to see the same behavior. I am at a loss to explain the nature of these behaviors when the Datadog AAS extension is introduced. It doesn't matter which version of the AAS extension we use, they all exhibit the same application impacts. We do not see similar patterns when using the Azure Application Insights APM extension. Any guidance/help would be appreciated.

**Comment by andrewlock** [comment]
Hi @jshrack-aya, really sorry to hear you're having issues. I think the best way to get this resolved is to open a support ticket with [support@datadoghq.com](mailto:support@datadoghq.com), so that we make sure we collect all the relevant details and investigate what's going on. Thanks!

**Comment by lucaspimentel** [comment]
Closing this issue as stale.
