### ISSUE TITLE
 "}" is missing at the end of logs when datadog extension on azure app service collects logs

### ISSUE THREAD

**Issue by clgcn** [DataDog/datadog-aas-extension#211]
Hi all,

We are using datadog extension on azure app service to collect logs by agentless APM, it is missing "}" at the end of logs when the  logs is deeply nested, the problem happen when json nested more than 3 layers.

The debug process as below:
1. I try to send logs to datadog by agentless serilog sink, the logs don't missing "}" at the end, the datadog give me a MessageTemplate event attributes, it doesn't missing "}" in this event attribute.
2. I try to write logs to Azure console, i check it in azure app service console , it doesn't missing "}" also.

**Comment by andrewlock** [comment]
Hi @clgcn - could you please clarify a couple of points:

- When you say "collect logs by agentless APM" you're using [this configuration, correct](https://docs.datadoghq.com/logs/log_collection/csharp/?tab=serilog#agentless-logging-with-apm)?
- Could you confirm which logging library you're using? Nlog/Serilog/Log4Net/ILogger?
- Could you provide an example of the log message you're sending (e.g. how you're writing the log message in code), and how it looks in Datadog?

Thanks!

**Comment by clgcn** [comment]
It is cause by the serilog, not datadog extension, thanks for you reply.
https://github.com/serilog/serilog-sinks-file/issues/102
