### ISSUE TITLE
Data Dog Agent v7.45 is 4.5 months out of date.

### ISSUE THREAD

**Issue by jwyza-pi** [DataDog/datadog-aas-extension#215]
Hello!  The current version that the Datadog AAS Extension has published includes the DD Agent version 7.45.0 (released on June 5th).  The current version is 7.48.1 which represents 3 "big" updates since.  Is there a particular blocker to updating to a more recent version?  My main impetous for wanting this is that https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm/?tab=net is listed as supporting only version 7.46+.

**Comment by joe-tiedeman-aplan** [comment]
I'd also be keen to see an update provided for the core Agent version, or at least understand the reasons for it being so out of date.

**Comment by jwyza-pi** [comment]
I've just opened an actual support ticket with DD regarding this.  The fact that it's now 7 months out of date and we've gotten 0 reply here means I'm not hopeful we're likely to get one.

**Comment by joe-tiedeman-aplan** [comment]
I'm going to talk to my account manager and see if I can get some sort of an update. They've been really receptive to other feedback/feature requests etc recently, so I'm hopeful that I should be able to get some sort of traction.

**Comment by jcstorms1** [comment]
@jwyza-pi My apologies for the delay and lack of communication on this issue. We had some concerns with multiple versions of the agent that delayed this update. Today we released [v2.43.1](https://github.com/DataDog/datadog-aas-extension/releases/tag/dotnet-v2.43.001) of the extension and it contains [v7.49.1](https://github.com/DataDog/datadog-agent/releases/tag/7.49.1) of the agent. If you have any additional concerns let us know, but I'll mark this one as closed for now. Again, apologies for the lack of communication.

**Comment by joe-tiedeman-aplan** [comment]
@jcstorms1 Many thanks for getting the update out - can I just confirm the version of the Agent in 2.43.1 - the release notes you link to say that it's 7.49, not the bugfix release of 7.49.1.  Can you also give us some details on what the concerns were and whether the lack of comms and updates should give us cause for concern over the reliability and future support of the extension? Could you also let us know what the plan is going forward for release cadence of the extension when Agent updates are released?

**Comment by joe-tiedeman-aplan** [comment]
Please can we get an answer to the plan for release cadence of Agent updates? I see that We're still on 7.49.0 and 7.51 so we're once again quite a bit out of date.
