### ISSUE TITLE
Microsoft.Extensions.Logging missing after upgrading to v9.0.0

### ISSUE THREAD

**Issue by RobARichardson** [DataDog/datadog-aas-extension#292]
Microsoft recently released v9.0.0 of their `Microsoft.Extensions.*` packages, including [Microsoft.Extensions.Logging](https://www.nuget.org/packages/microsoft.extensions.logging). These packages still target .NET 8.  After upgrading multiple .NET 8 Applications to these new packages, we're no longer seeing logs from `Microsoft.Extensions.Logging` show up in Datadog.  These applications all use [Agentless Logging with APM](https://docs.datadoghq.com/logs/log_collection/csharp/?tab=serilog#agentless-logging-with-apm). If we revert back to the v8 version of these packages, logs show up again.

These App Services are all using the latest version of the AAS Extension v3.5.000
https://github.com/DataDog/datadog-aas-extension/releases/tag/dotnet-v3.5.000

**Comment by andrewlock** [comment]
[Support for .NET 9 has been merged ](https://github.com/DataDog/dd-trace-dotnet/pull/6265), and will be in the next release (3.6.0) but it has not been released yet.

**Comment by andrewlock** [comment]
Hi, .NET 9 support has been released in 3.6.000 - do let us know if you have any issues. Thanks!

**Comment by RobARichardson** [comment]
After updating the extension, we can see logs again. Thank for the quick release!

**Comment by RobARichardson** [comment]
@andrewlock when I originally created this issue, we were seeing this behavior for ASP.NET APIs. While those are working fine now, we're still seeing the same behavior I [described above](https://github.com/DataDog/datadog-aas-extension/issues/292#issue-2664706432) for Azure Function Apps using the [Isolated Worker model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Cwindows). Same setup - .NET 8 using the `Microsoft.Extensions.*` v9 libraries. Is this behavior expected?

**Comment by RobARichardson** [comment]
> [@andrewlock](https://github.com/andrewlock) when I originally created this issue, we were seeing this behavior for ASP.NET APIs. While those are working fine now, we're still seeing the same behavior I described above for Azure Function Apps using the [Isolated Worker model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Cwindows). Same setup - .NET 8 using the `Microsoft.Extensions.*` v9 libraries. Is this behavior expected?

Please disregard. After more investigation, we believe the issue is due to #295.
